<a href="https://colab.research.google.com/github/victormaciase/EconometriaFinanciera_MagisterFinanzasWK/blob/main/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
url_data = "https://raw.githubusercontent.com/victormaciase/EconometriaFinanciera_MagisterFinanzasWK/refs/heads/main/Lab1/loan50.csv"

In [4]:
# Leer el archivo CSV directamente desde url
df = pd.read_csv(url_data)

## Pregunta 1
Presenta los datos

In [5]:
df

,state,emp_length,term,homeownership,annual_income,verified_income,debt_to_income,total_credit_limit,total_credit_utilized,num_cc_carrying_balance,loan_purpose,loan_amount,grade,interest_rate,public_record_bankrupt,loan_status,has_second_income,total_income
0,NJ,3.0,60,rent,59000,Not Verified,0.557525,95131,32894,8,debt_consolidation,22000,B,10.90,0,Current,False,59000
1,CA,10.0,36,rent,60000,Not Verified,1.305683,51929,78341,2,credit_card,6000,B,9.92,1,Current,False,60000
2,SC,NaN,36,mortgage,75000,Verified,1.056280,301373,79221,14,debt_consolidation,25000,E,26.30,0,Current,False,75000
3,CA,0.0,36,rent,75000,Not Verified,0.574347,59890,43076,10,credit_card,6000,B,9.92,0,Current,False,75000
4,OH,4.0,60,mortgage,254000,Not Verified,0.238150,422619,60490,2,home_improvement,25000,B,9.43,0,Current,False,254000
5,IN,6.0,36,mortgage,67000,Source Verified,1.077045,349825,72162,4,home_improvement,6400,B,9.92,0,Current,False,67000
6,NY,2.0,36,rent,28800,Source Verified,0.099722,15980,2872,1,debt_consolidation,3000,D,17.09,0,Current,False,28800
7,MO,10.0,36,mortgage,80000,Not Verified,0.350913,258439,28073,3,credit_card,14500,A,6.08,0,Current,False,80000
8,FL,6.0,60,rent,34000,Not Verified,0.697500,87705,23715,10,credit_card,10000,A,7.97,0,Current,False,34000
9,FL,3.0,60,mortgage,80000,Source Verified,0.166854,330394,32036,4,debt_consolidation,18500,C,12.62,1,Current,True,192000
10,MD,8.0,36,rent,73000,Source Verified,0.414329,36182,30246,3,debt_consolidation,17000,D,17.09,0,Current,False,73000
11,HI,10.0,36,mortgage,120000,Not Verified,0.798908,452712,95869,4,credit_card,12000,A,5.31,0,Current,False,120000
12,CT,10.0,36,rent,100000,Source Verified,0.278090,74805,27809,3,credit_card,16000,A,7.35,0,Current,False,100000
13,NE,2.0,36,mortgage,105000,Not Verified,0.268190,279386,28160,2,home_improvement,16500,A,5.31,0,Current,False,105000
14,CA,5.0,36,rent,34000,Not Verified,0.629294,33038,21396,3,debt_consolidation,3000,A,7.96,0,Current,False,34000
15,TX,2.0,60,mortgage,98000,Verified,1.107102,319551,108496,6,credit_card,29400,E,24.85,0,Fully Paid,False,98000
16,HI,5.0,60,rent,68700,Source Verified,1.499549,119325,103019,5,debt_consolidation,13500,D,18.06,0,Current,False,68700
17,CA,3.0,60,rent,43000,Source Verified,0.154653,60693,22270,4,debt_consolidation,18200,B,10.42,0,Current,True,144000
18,CA,3.0,36,rent,100000,Source Verified,0.138230,69100,13823,5,other,6000,A,7.96,0,Current,False,100000
19,FL,10.0,60,mortgage,76000,Source Verified,0.589816,249700,44826,10,debt_consolidation,18000,D,19.42,0,Current,False,76000
20,MS,10.0,36,mortgage,80000,Verified,0.737306,136046,124994,1,car,5000,C,14.08,0,Current,True,169528
21,WI,10.0,60,mortgage,50000,Verified,0.523417,375828,87934,11,debt_consolidation,40000,D,20.00,0,Fully Paid,True,168000
22,WV,0.0,36,mortgage,80000,Not Verified,0.704538,197299,56363,6,debt_consolidation,4500,B,9.44,0,Fully Paid,False,80000
23,CA,1.0,36,rent,185000,Not Verified,0.254676,102500,47115,2,credit_card,15000,B,9.92,0,Current,False,185000
24,NJ,5.0,60,mortgage,42000,Source Verified,0.086667,64800,3640,5,house,20000,B,10.91,0,Current,False,42000
25,MA,2.0,36,rent,100000,Verified,0.328196,144700,88613,4,small_business,20000,A,5.32,0,Current,True,270000
26,TX,5.0,36,mortgage,65000,Not Verified,0.242738,256974,15778,7,debt_consolidation,10000,A,6.71,0,Fully Paid,False,65000
27,IN,5.0,36,own,45000,Not Verified,0.157311,121323,7079,4,debt_consolidation,9000,C,15.04,0,Current,False,45000
28,RI,10.0,60,mortgage,245000,Verified,0.167363,495163,41004,6,credit_card,35000,B,11.98,0,Current,False,245000
29,TX,0.0,36,mortgage,50000,Source Verified,0.639677,203326,122818,4,debt_consolidation,40000,C,12.62,0,Current,True,192000
30,VA,0.0,36,rent,116000,Source Verified,0.584397,446850,67790,7,debt_consolidation,13125,B,10.91,0,Current,False,116000
31,NV,5.0,36,mortgage,30000,Not Verified,0.512009,190832,57345,6,home_improvement,32000,B,9.44,0,Current,True,112000
32,MA,4.0,60,mortgage,80000,Not Verified,0.244541,432092,53310,5,debt_consolidation,18000,B,9.93,0,Current,True,218000
33,CA,7.0,36,rent,103000,Source Verified,0.265835,124900,27381,5,other,30000,A,7.35,0,Fully Paid,False,103000
34,IL,5.0,36,rent,58000,Not Verified,4.777259,236668,277081,5,credit_card,4400,D,18.45,0,Current,False,58000
35,AZ,0.0,36,own,55000,Source Verified,0.299091,35900,16450,12,debt_consolidation,7000,D,17.09,0,Current,False,55000
36,MN,NaN,36,mortgage,65000,Not Verified,0.752246,174860,48896,4,credit_card,25000,A,7.96,0,Current,False,65000
37,IL,2.0,36,rent,32000,Source Verified,0.721281,45594,23081,4,renewable_energy,6500,A,6.08,1,Current,False,32000
38,MD,5.0,36,mortgage,325000,Source Verified,0.307751,793009,100019,11,credit_card,35000,A,6.71,0,Current,False,325000
39,MD,3.0,36,rent,70000,Source Verified,5.333729,272878,373361,2,other,7500,A,7.34,0,Current,False,70000
40,CA,10.0,60,mortgage,160000,Verified,0.334400,581604,53504,3,debt_consolidation,38500,C,12.62,1,Current,False,160000
41,NJ,6.0,36,rent,50000,Source Verified,1.257440,90398,62872,5,credit_card,15000,C,16.02,0,Current,False,50000
42,IL,10.0,60,rent,71000,Not Verified,0.742521,115970,52719,8,car,24000,B,10.90,0,Current,False,71000
43,MI,0.0,36,mortgage,85000,Not Verified,0.818765,131847,69595,3,debt_consolidation,24000,B,9.93,0,Fully Paid,False,85000
44,CA,5.0,36,mortgage,87000,Source Verified,0.054724,294946,4761,3,debt_consolidation,12800,B,9.44,0,Current,False,87000
45,TX,10.0,36,mortgage,60000,Not Verified,0.731183,64017,43871,5,home_improvement,6000,B,10.42,0,Current,False,60000
46,NV,0.0,36,mortgage,58500,Verified,0.396821,49234,23214,2,debt_consolidation,30000,D,21.45,0,Current,False,58500
47,NH,2.0,36,rent,50000,Source Verified,0.502620,39814,25131,4,debt_consolidation,5825,B,10.91,0,Current,False,50000
48,IL,2.0,36,own,103000,Not Verified,0.973592,150027,100280,4,debt_consolidation,20000,B,9.43,0,Current,False,103000
49,TX,9.0,36,mortgage,77500,Verified,0.677858,390156,52534,2,other,15000,A,6.08,0,Current,False,77500

## Pregunta 2

¿Cuántas observaciones hay en el dataset? ¿Cuántas variables?

In [8]:
df.shape

(50, 18)

## Pregunta 3
¿Qué variables incluye la base de datos?

In [9]:
df.columns

Index(['state', 'emp_length', 'term', 'homeownership', 'annual_income',
       'verified_income', 'debt_to_income', 'total_credit_limit',
       'total_credit_utilized', 'num_cc_carrying_balance', 'loan_purpose',
       'loan_amount', 'grade', 'interest_rate', 'public_record_bankrupt',
       'loan_status', 'has_second_income', 'total_income'],
      dtype='object')

## Pregunta 4
¿Qué tipo de datos incluye cada variable?

In [10]:
df.dtypes

state                       object
emp_length                 float64
term                         int64
homeownership               object
annual_income                int64
verified_income             object
debt_to_income             float64
total_credit_limit           int64
total_credit_utilized        int64
num_cc_carrying_balance      int64
loan_purpose                object
loan_amount                  int64
grade                       object
interest_rate              float64
public_record_bankrupt       int64
loan_status                 object
has_second_income             bool
total_income                 int64
dtype: object

## Pregunta 5
¿Qué tipo de variable es *homeownership*? Construye una tabla de frecuencias absoluta y porcentual.

In [7]:
df['homeownership'].value_counts()  # frecuencia absoluta

homeownership
mortgage    26
rent        21
own          3
Name: count, dtype: int64

In [9]:
df['homeownership'].value_counts(normalize = True)*100    # frecuencia porcentual

homeownership
mortgage    52.0
rent        42.0
own          6.0
Name: proportion, dtype: float64